name: Build on Release

on:
  release:
    types: [created]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Build project
      run: |
        go build -o koksmat

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mac-build
        path: koksmat

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Build project
      run: |
        go build -o koksmat.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: koksmat.exe
